# Generated by Django 5.1.5 on 2025-02-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeContent', '0002_userregistration_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
